# Use the official MySQL image as the base image
FROM mysql:8.0

# Set the root password for MySQL (change it to your desired password)
ENV MYSQL_ROOT_PASSWORD=root_

# Create a directory to store the SQL file
WORKDIR /docker-entrypoint-initdb.d

# Copy the SQL file into the container
COPY fashion_app.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
