version: '3'
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443 
  db:
    image: mysql:latest
    environtment:
      - MYSQL_DATABASE=fashion_app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environtment:
      - PMA_HOST=db
      - pma_port=3306
