# Use an official MySQL image as a parent image
FROM mysql:8.0

# Set the root password
ENV MYSQL_ROOT_PASSWORD=root_

# Create a database and user
ENV MYSQL_DATABASE=fashion_app
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=

# Expose port 3306 to the outside world
EXPOSE 3306
